### ISSUE TITLE
[FEATURE REQUEST] display full filenames?

### ISSUE THREAD

**Issue by Crudefern** [masterfeizz/DaedalusX64-3DS#101]
I have multiple SM64 rom hacks in the roms folder but i can't tell which is which because they all display as super mario 64. it would be nice to have a setting to toggle full filenames. it's probably easy to implement but i don't know how to code. (sorry if i misspell something)

**Comment by masterfeizz** [comment]
Press L

**Comment by Crudefern** [comment]
ok thx
