### ISSUE TITLE
Crash on B3313 startup

### ISSUE THREAD

**Issue by egor835** [masterfeizz/DaedalusX64-3DS#108]
I tried B3313 romhack for sm64, luma crashes after startup sound with that:
![IMG_20230206_215109](https://user-images.githubusercontent.com/90187830/217059885-cbbffeb9-a550-4808-8685-11ae3088bfd7.jpg)
And, there is no sound for spamton64 romhack, any fixes?

**Comment by soup6020** [comment]
I am not a developer of this project, but b3313 is a SM64 romhack that depends on specific inaccuracies of the GLideN64 video plugin intended for Mupen64Plus or Project64. DaedalusX64 does not use video plugins, so there is no easy way to support this romhack. You will unfortunately only be able to play b3313 on one of the aforementioned emulators, configured with GLideN64 in HLE mode, with the HLE RSP. Hope this helps.

**Comment by egor835** [comment]
Oh, I understand then, thanks
