### ISSUE TITLE
Severe graphical glitches in SM64 and Kirby 64

### ISSUE THREAD

**Issue by autofire372** [masterfeizz/DaedalusX64-3DS#40]
I tested the latest master build, and there are serious palette/texture issues in both Super Mario 64 and Kirby 64.

Here's an ingame shot of SM64:
![2020-05-17_00-02-15 076_top](https://user-images.githubusercontent.com/8486750/82135715-d3786d80-97d3-11ea-80ab-fc2d1234d72b.jpg)

And here's what Kirby 64's title screen looks like right now:
![2020-05-17_00-07-08 047_top](https://user-images.githubusercontent.com/8486750/82135721-ef7c0f00-97d3-11ea-8c34-aaf396390104.jpg)

**Comment by masterfeizz** [comment]
You are using an outdated version of picaGL to compile.

**Comment by autofire372** [comment]
Alright, I'll update picaGL and recompile, then. Thanks for the tip.
