### ISSUE TITLE
Ignore this bug

### ISSUE THREAD

**Issue by BlowZed** [masterfeizz/DaedalusX64-3DS#58]
Describe the bug
When playing Donkey Kong 64, you cannon get past Cranky's training because it is impossible to throw oranges which you need to do in one of the levels. 

To Reproduce
Steps to reproduce the behavior: Go to the area with the four barrels that Cranky tells you to complete and go to the back left barrel. You'll find that there is no way to throw an orange since there are no c buttons on 3ds consoles.

Expected behavior
There should be some way to throw oranges. The d-pad could maybe act as the c buttons (d-pad up would be up c, d-pad right would be right c, etc.)

Screenshots

Device:
 - FW:11.13-45U on the new 2ds xl
 - Daedalus Version 0.2

Additional context

**Comment by BlowZed** [comment]
Nevermind, just solved my own problem. You have to use the c stick. Silly me XD

**Comment by MisterPrintf** [comment]
Mind closing the issue?
