### ISSUE TITLE
Bottom screen daedalus ?

### ISSUE THREAD

**Issue by G9-Dev** [masterfeizz/DaedalusX64-3DS#81]
As N64 is 4:3, it should be logic to use bottom screen, or having a setting to change it.
(I have a 3DS with a broken screen ...)

**Comment by G9-Dev** [comment]
Close

**Comment by foxsouns** [comment]
you could try forking it and making it use the bottom screen, if you want to have it
this is opensource for a reason

**Comment by G9-Dev** [comment]
> you could try forking it and making it use the bottom screen, if you want to have it
> this is opensource for a reason

Sadly I have a 32bit computer, so I can’t have devkitpro :( 
Thanks anyway for ur reply :3

**Comment by foxsouns** [comment]
you might be able to after all. if you're using windows, you can follow the stuff [here](https://devkitpro.org/wiki/devkitPro_pacman#Customising_Existing_Pacman_Install). you can direct any help questions to [my email](mailto://renastics@protonmail.ch) if you want.

**Comment by G9-Dev** [comment]
> you might be able to after all. if you're using windows, you can follow the stuff [here](https://devkitpro.org/wiki/devkitPro_pacman#Customising_Existing_Pacman_Install). you can direct any help questions to [my email](mailto://renastics@protonmail.ch) if you want. you'll need x86 msys2 installed, first.

Hi,
There is some errors with MSYS2 when installing keys. I'm gonna install Linux. :3

**Comment by foxsouns** [comment]
Linux will have the same keyserver problems; you need to find the right server. ie: instead of ubuntu.keyserver.org or whatever it is; you'd need to find the one that works and put it instead
ill go and see if i can find it

**Comment by foxsouns** [comment]
`--keyserver hkp://ipv4.pool.sks-keyservers.net:11371`

**Comment by foxsouns** [comment]
got answer from here
https://devkitpro.org/viewtopic.php?f=15&t=9000

**Comment by G9-Dev** [comment]
Thanks much, I'm gonna try it later.
 Notice that the error in the thread isnt the same as mine.
Hope it works :3

**Comment by G9-Dev** [comment]
Thanks it now works !!
I can finally code my games, thank you !

**Comment by foxsouns** [comment]
Woo! Good gob man, have fun and make us some homebrew :>
