### ISSUE TITLE
[BUG] Stuck on rom selection.

### ISSUE THREAD

**Issue by AlbertCoolGuy** [masterfeizz/DaedalusX64-3DS#9]
Describe the bug
I try to run DaedalusX64-3DS, but it gets stuck on the rom selector screen where all input is supressed/doesn't do anything.

To Reproduce
Open DaedalusX64-3DS on a O2DS and try to move up and down on the rom selection screen.

Expected behavior
It should let me select a rom to run.

Screenshots

Device:
 - FW: 11.13.0-45E
 - Daedalus Version: 0.2
 - Console: O2DS

Additional context

**Comment by L-i-n-u-x-C-a-t** [comment]
You are using an old 2DS so it is kinda normal that nothing works. The emulator is higly recommended to use on New 3DS/2DS

**Comment by AlbertCoolGuy** [comment]
I know, but how would I be able to fix it?

**Comment by L-i-n-u-x-C-a-t** [comment]
try to uninstall/reinstall it. Did you install it correctly at first? the cia + extracting the .zip?

**Comment by AlbertCoolGuy** [comment]
Yeah, here is my DaedalusX64 folder. I can try reinstalling.
[DaedalusX64.zip](https://github.com/masterfeizz/DaedalusX64-3DS/files/4587400/DaedalusX64.zip)

**Comment by renotek15** [comment]
You need to dump DSP again.

**Comment by AlbertCoolGuy** [comment]
DSP?


Den tir. 12. maj 2020 kl. 10.08 skrev renotek15 <notifications@github.com>:

**Comment by zenseii** [comment]
Install and run this .cia to dump it:
https://github.com/zoogie/DSP1/releases

Then run daeadlusx64 and see if you have the same problem.

**Comment by AlbertCoolGuy** [comment]
Oh, ok.

**Comment by AlbertCoolGuy** [comment]
It's working now! Thanks!

**Comment by AlbertCoolGuy** [comment]
Just a quick question. Is it possible to improve o2ds performance in any way?
